# Site settings
title: Bo's personal site
email: cupidcb[at]gmail[dot]com
description: > # this means to ignore newlines until "baseurl:"
  Developpment can be a hobby, so does it for me  :)
  You can find my sites: demo, cv, bookmark etc.
  If you want to follow my activities, find in my blog :
  cuiborails.wordpress.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cui-bo.github.io" # the base hostname & protocol for your site
twitter_username: cupidcb
github_username:  cui-bo

# Build settings
markdown: kramdown

include:
  - _data
  - bookmark
  - pinterest
  - cv
  - demo
  - puzzle
  - scroll
  - sudoku
  - timer
